name: JumpIn
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.1.0+34
#1.0.0+4 people update4
#1.0.0+5 people update5
#1.0.0+7 people is stable with request update working
#1.0.0+8 people is stable with all fix
#1.0.0+11 people is stable with all fix now

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  firebase_crashlytics: ^2.0.3
  lottie: any
  google_sign_in: ^5.0.3
  cloud_firestore: ^2.1.0
  firebase_storage: ^8.0.6
  cupertino_icons: ^1.0.3
  #for Either in value_objects
  dartz: ^0.9.2
  #used for union of failures in valueOobjects
  freezed_annotation: ^0.14.2
  shared_preferences: any
  rect_getter: ^1.0.0
  liquid_swipe: ^2.1.0
  page_transition: ^2.0.2
  auto_size_text: ^2.1.0
  curved_navigation_bar: ^0.3.7
  flutter_bloc: ^7.0.0
  get_it: ^7.1.3
  injectable: ^1.4.0
  intl_phone_field: ^2.0.0
  flutter_swiper: ^1.1.6
  quiver: ^3.0.1
  flutter_datetime_picker: ^1.5.1
  image_picker: ^0.8.0+3
  flappy_search_bar: any
  device_preview: any
  animated_splash_screen: any
  percent_indicator: ^3.0.1
  flutter_spinkit: ^5.0.0
  data_connection_checker: ^0.3.4
  flutter_launcher_icons: any
  geolocator: ^7.0.3
  geocoder: ^0.2.1
  geoflutterfire: any
  day_night_time_picker: ^1.0.2
  badges: ^2.0.1
  get: ^4.1.4
  share: ^2.0.1
  http: ^0.13.3
  path_provider: any
  permission_handler: ^6.0.1+1
  rxdart: ^0.27.0
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^5.0.0
  provider: ^5.0.0
  flutter_neumorphic: ^3.1.0
  scrollable_positioned_list: ^0.1.10
  keyboard_dismisser: ^2.0.0
  image_stack: ^2.0.1
  flutter_facebook_login: ^3.0.0
  flutter_facebook_auth: ^3.3.3+1
  contacts_service: ^0.6.1
  material_floating_search_bar: ^0.3.4
  liquid_progress_indicator: ^0.3.2
  firebase_dynamic_links: ^2.0.4
  flutter_inappwebview: ^5.3.2
  introduction_screen: ^2.1.0
  app_settings: ^4.1.0
  emoji_feedback: ^0.1.0
  location: ^4.1.1
  google_maps_flutter: ^2.0.6
  google_maps_place_picker: ^2.0.0-nullsafety.3
  country_list_pick: ^1.0.1+4
  devicelocale: ^0.4.1
  cached_network_image: ^3.1.0-alpha.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator: ^1.0.6

flutter_icons:
  image_path: "assets/icon/icon1_circle.png" 
  android: true
  ios: true
  # adaptive_icon_background: "assets/icon/android_launcher_bg.png"
  # adaptive_icon_foreground: "assets/icon/rsz_logo_white.png"
  



# The following section is specific to Flutter.
flutter:
  fonts:
    - family: TrebuchetMS
      fonts:
        - asset: assets/fonts/Trebuchet MS.ttf
        - asset: assets/fonts/SFUIText-Bold.ttf
        - asset: assets/fonts/SFUIText-Semibold.ttf
    
    - family: AirbnbCereal
      fonts: 
        - asset: assets/fonts/AirbnbCereal-Light.ttf
          weight: 300
        - asset: assets/fonts/AirbnbCereal-Book.ttf
          weight: 400
        - asset: assets/fonts/AirbnbCereal-Medium.ttf
          weight: 500
        - asset: assets/fonts/AirbnbCereal-Bold.ttf
          weight: 700
        - asset: assets/fonts/AirbnbCereal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AirbnbCereal-Black.ttf
          weight: 900

  uses-material-design: true

  assets:
    - assets/images/Home/
    - assets/images/Onboarding/
    - assets/animations/
    - assets/images/SideNav/
    - assets/images/Onboarding/Interests/outdoor-sports/
    - assets/images/Onboarding/Interests/indoor-sports/
    - assets/images/Onboarding/Interests/academic/
    - assets/images/Onboarding/Interests/causes-passionate-about/
    - assets/images/Onboarding/Interests/competitve-exams/
    - assets/images/Onboarding/Interests/entertainment/
    - assets/images/Onboarding/Interests/fandoms/
    - assets/images/Onboarding/Interests/foods-&-drinks/
    - assets/images/Onboarding/Interests/games/
    - assets/images/Onboarding/Interests/health-&-fitness/
    - assets/images/Onboarding/Interests/hobbies/
    - assets/images/Onboarding/Interests/miscellaneous/
    - assets/images/Onboarding/Interests/travel-&-adventure/
    - assets/images/Onboarding/Interests/career/
    - assets/images/Profile/
    - assets/images/chats/

